name: Validate JSON

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate blackbox-exporter.json
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: cat blackbox-exporter/blackbox-exporter.json | jq empty
